import { Inter } from "next/font/google";
import { Box, ChakraProvider } from "@chakra-ui/react";
import NProgress from "nprogress";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box maxWidth="1280px" m="auto">
            <header>Navbar</header>
            <main>{children}</main>
            <footer>Footer</footer>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
